Repository codestates-seb/seb44_main_018, pull requests merged in 2023-07, with the labels that each got.

#60 Feat: Profile 공통 컴포넌트 완성
  client/src/common/profile/Profile.styled.tsx
  client/src/common/profile/Profile.tsx
  client/tailwind.config.js
Labels: 스타일, 추가

#59 Feat: 라우터 경로 설정 및 페이지 설정
  client/src/pages/copyPopUp/CopyPopUp.tsx
  client/src/pages/feedEditing/FeedEditing.tsx
  client/src/pages/feedPopUp/FeedPopUp.tsx
  client/src/pages/feedPosting/FeedPosting.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/info/Info.tsx
  client/src/pages/infoEditing/InfoEditing.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/notFound/NotFound.tsx
  client/src/pages/userpage/UserPage.tsx
  client/src/pages/walkEditing/WalkEditing.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
  client/src/pages/walkMate/WalkMate.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
  client/src/routers/paths.ts
  client/src/routers/routers.tsx
Labels: 추가, 주기능

#58 Style: Footer 컴포넌트 디자인 완성
  client/src/assets/github.svg
  client/src/assets/notion.svg
  client/src/common/footer/Footer.styled.tsx
  client/src/common/footer/Footer.tsx
  client/src/common/nothing
Labels: 스타일, 추가

#61 Feat : Button Component 구현
  client/.eslintrc.cjs
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/common/button/Button.tsx
  client/src/common/button/button.styled.tsx
  client/src/stories/Button.stories.ts
  client/src/stories/Button.tsx
Labels: 스타일, 추가, 주기능

#63 Feat: 팝업 페이지 공통 컴포넌트 추가
  client/src/App.tsx
  client/src/common/button/Button.tsx
  client/src/common/button/button.styled.tsx
  client/src/common/popup/Popup.tsx
  client/src/common/popup/popup.styled.tsx
  client/src/main.tsx
  client/src/types/buttonType.tsx
  client/tailwind.config.js
Labels: 스타일, 추가, 수정, 주기능

#68 Refactor: SideNav, FeedCard 컴포넌트 라우팅 경로 설정
  client/package-lock.json
  client/package.json
  client/src/assets/button/like.svg
  client/src/common/button/Button.tsx
  client/src/common/button/button.styled.tsx
  client/src/common/footer/Footer.tsx
  client/src/common/popup/Popup.tsx
  client/src/components/card/feedCard/FeedCard.styled.tsx
  client/src/components/card/feedCard/FeedCard.tsx
  client/src/components/card/feedCard/styles.css
  client/src/components/card/sidenav/SideNav.tsx
  client/src/index.css
  client/src/types/propType.tsx
Labels: 스타일, 추가, 주기능

#73 Feat&Style: 게시물 작성 컴포넌트 구현 완료
  client/src/App.tsx
  client/src/assets/button/close.svg
  client/src/assets/button/plus.svg
  client/src/assets/button/write.svg
  client/src/common/popup/Popup.tsx
  client/src/common/popup/popup.styled.tsx
  client/src/components/card/feedCard/FeedCard.styled.tsx
  client/src/components/card/feedwritecard/FeedEditCard.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.styled.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/components/card/feedwritecard/carousel.css
  client/src/index.css
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/tailwind.config.js
Labels: 스타일, 추가, 주기능

#75 Fe feat/components comment
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/mutationfn.ts
  client/src/common/button/Button.tsx
  client/src/common/comment/Comment.tsx
  client/src/common/comment/comment.styled.tsx
  client/src/types/commentType.ts
  client/src/types/propType.ts
  client/src/util/changeTiem.ts
Labels: 스타일, 추가, 주기능

#80 Feat: Info Page 컴포넌트 완성
  client/src/App.tsx
  client/src/common/input/Input.styled.tsx
  client/src/common/select/select.styled.tsx
  client/src/index.css
  client/src/pages/info/Info.styled.tsx
  client/src/pages/info/Info.tsx
Labels: 스타일, 추가, 주기능

#81 Feat&Style: 메인 피드카드 사이드네브바 추가 및 메인 페이지 구현완료
  client/src/App.tsx
  client/src/assets/button/like.svg
  client/src/common/carousel/carousel.css
  client/src/common/header/Header.styled.tsx
  client/src/components/card/feedCard/FeedCard.styled.tsx
  client/src/components/card/feedCard/FeedCard.tsx
  client/src/components/card/feedCard/styles.css
  client/src/components/card/feedwritecard/FeedEditCard.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/components/card/feedwritecard/carousel.css
  client/src/components/card/sidenav/SideNav.styled.tsx
  client/src/components/card/sidenav/SideNav.tsx
  client/src/index.css
  client/src/pages/home/Home.styled.tsx
  client/src/pages/home/Home.tsx
Labels: 버그, 스타일, 추가, 수정, 리팩토링

#82 Feat: 펫 등록 팝업 페이지 작성
  client/.eslintrc.cjs
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/api/mutationfn.ts
  client/src/assets/label/man.svg
  client/src/assets/label/woman.svg
  client/src/common/comment/Comment.tsx
  client/src/common/header/Header.styled.tsx
  client/src/common/input/Input.styled.tsx
  client/src/common/popup/Popup.tsx
  client/src/common/popup/popup.styled.tsx
  client/src/common/profile/Profile.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.styled.tsx
  client/src/components/pet/PetInfo.tsx
  client/src/components/pet/petInfo.styled.tsx
  client/src/components/pet/petProfile/PetProfile.tsx
  client/src/components/pet/petProfile/petProfile.styled.tsx
  client/src/pages/home/Home.tsx
  client/src/util/dataUrltoFile.ts
Labels: 스타일, 추가, 주기능

#85 Fix: Select Component 오류 수정
  client/src/common/select/Select.tsx
  client/src/hook/useZipCode.tsx
  client/src/pages/info/Info.tsx
Labels: 버그, 수정, 리팩토링

#83 Feat&Style: Info/InfoEditing 페이지 구현완료
  client/src/App.tsx
  client/src/api/mutationfn.ts
  client/src/api/queryfn.ts
  client/src/common/input/Input.styled.tsx
  client/src/pages/info/Info.styled.tsx
  client/src/pages/info/Info.tsx
  client/src/routers/routers.tsx
Labels: 버그, 스타일, 추가, 주기능

#87 Fix&Style: FeedPosting 컴포넌트 스타일 수정 및 컴포넌트 조건부 렌더링 추가
  client/src/App.tsx
  client/src/common/popup/popup.styled.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
Labels: 스타일, 수정, 주기능

#88 Feat&Refactor: Oauth 구현 및 로딩페이지 생성
  client/src/App.tsx
  client/src/assets/illustration/loading-dog.png
  client/src/assets/loading-text.svg
  client/src/assets/loading.svg
  client/src/common/header/Header.tsx
  client/src/pages/loading/Loading.styled.tsx
  client/src/pages/loading/Loading.tsx
  client/src/pages/login/Login.tsx
  client/src/routers/paths.ts
  client/src/routers/routers.tsx
Labels: 스타일, 추가, 수정, 리팩토링, 주기능

#91 Feat: 마이 페이지 일부 작성
  client/src/api/mutationfn.ts
  client/src/api/queryfn.ts
  client/src/api/url.ts
  client/src/assets/button/pet-check.svg
  client/src/assets/button/plus.svg
  client/src/common/comment/Comment.tsx
  client/src/common/popup/popup.styled.tsx
  client/src/components/follow-list/FollowList.tsx
  client/src/components/follow-list/followList.styled.tsx
  client/src/components/pet/PetInfo.tsx
  client/src/components/plus-button/PlusBtn.tsx
  client/src/components/plus-button/plusBtn.styled.tsx
  client/src/components/user_my_page/pet-container/PetContainer.tsx
  client/src/components/user_my_page/pet-container/petContainer.styled.tsx
  client/src/components/user_my_page/petinfo-box/PetInfoBox.tsx
  client/src/components/user_my_page/petinfo-box/petInfoBox.styled.tsx
  client/src/pages/info/Info.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/myPage/myPage.styled.tsx
  client/src/types/commentType.ts
  client/src/types/feedTypes.ts
  client/src/types/petType.ts
  client/src/types/userType.ts
  client/src/util/changeTiem.ts
Labels: 스타일, 추가, 주기능

#101 Fix : my page 수정
  client/src/api/mutationfn.ts
  client/src/components/pet/PetInfo.tsx
  client/src/components/user_my_page/pet-container/PetContainer.tsx
  client/src/pages/myPage/MyPage.tsx
Labels: 수정, 주기능

#107 Feat: 피드 게시물 가져오기 구현 완료
  client/src/api/mutationfn.ts
  client/src/api/queryfn.ts
  client/src/assets/button/like.svg
  client/src/assets/illustration/followingcat.png
  client/src/common/header/Header.tsx
  client/src/components/card/sidenav/SideNav.styled.tsx
  client/src/components/card/sidenav/SideNav.tsx
  client/src/pages/home/Home.styled.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/loading/Loading.tsx
Labels: 추가, 수정, 주기능

#111 Feat : 카카오 맵 api 추가
  client/index.html
  client/src/api/mutationfn.ts
  client/src/components/map/Map.tsx
  client/src/components/pet/PetInfo.tsx
  client/src/components/subscribe/Subscribe.tsx
  client/src/index.css
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
  client/tsconfig.json
Labels: 추가, 수정, 주기능

#115 Refactor : memberId store refactoring
  client/src/common/header/Header.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/components/follow-list/FollowList.tsx
  client/src/components/map/Map.tsx
  client/src/components/pet/PetInfo.tsx
  client/src/components/subscribe/Subscribe.tsx
  client/src/components/user_my_page/pet-container/PetContainer.tsx
  client/src/main.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/loading/Loading.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/userpage/UserPage.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
  client/src/store/Context.tsx
Labels: 수정, 리팩토링

#117 Refactor: Header component, UserPage component 리팩토링
  client/src/common/comment/Comment.tsx
  client/src/common/header/Header.tsx
  client/src/components/notice/NoticeNoData.tsx
  client/src/pages/myPage/MyPage.tsx
Labels: 리팩토링

#120 Fix: context API 적용
  client/src/api/mutationfn.ts
  client/src/assets/label/kakao-talk.svg
  client/src/common/comment/Comment.tsx
  client/src/common/footer/Footer.styled.tsx
  client/src/common/header/Header.tsx
  client/src/components/card/sidenav/SideNav.tsx
  client/src/components/card/walkCard/walkCard.tsx
  client/src/components/map-make/Map.tsx
  client/src/components/map-show/ShowMap.tsx
  client/src/components/user_my_page/pet-container/PetContainer.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/loading/Loading.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/walkEditing/WalkEditing.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
  client/src/store/Context.tsx
  client/src/util/changeDateFormat.ts
Labels: 버그, 수정, 리팩토링

#122 Feat: 웰컴팝업 컴포넌트 구현
  client/src/assets/illustration/pet-friends.png
  client/src/index.css
  client/src/pages/home/CricleProgressBar.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/loading/Loading.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/userpage/UserPage.tsx
Labels: 추가, 주기능

#126 Feat: 피드 게시물 수정 기능 구현 완료
  client/src/App.tsx
  client/src/api/mutationfn.ts
  client/src/common/comment/feedComment.tsx/FeedComment.styled.tsx
  client/src/common/comment/feedComment.tsx/FeedComment.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/main.tsx
  client/src/pages/feedEditing/FeedEditing.tsx
  client/src/pages/feedPopUp/FeedPopUp.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/routers/routers.tsx
  client/src/util/parseImg.ts
Labels: 추가, 리팩토링, 주기능

#127 Feat: useInfiniteQuery를 활용한 무한 스크롤 구현
  client/src/common/header/Header.tsx
  client/src/common/select/Select.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/walkMate/WalkMate.tsx
Labels: 추가, 주기능

#129 Fix: 무한 스크롤 버그 수정
  client/src/common/select/Select.tsx
  client/src/pages/walkMate/WalkMate.tsx
Labels: 버그, 수정

#130 Feat&Style: Grid스타일 수정 및 NavBar 컴포넌트 구현
  client/src/App.tsx
  client/src/assets/mobile/home-active-app.svg
  client/src/assets/mobile/home-app.svg
  client/src/assets/mobile/login-app.svg
  client/src/assets/mobile/logout-app.svg
  client/src/assets/mobile/mypage-active-app.svg
  client/src/assets/mobile/mypage-app.svg
  client/src/assets/mobile/post-active-app.svg
  client/src/assets/mobile/post-app.svg
  client/src/assets/mobile/walk-active-app.svg
  client/src/assets/mobile/walk-app.svg
  client/src/common/header/Header.styled.tsx
  client/src/common/select/select.styled.tsx
  client/src/components/card/walkCard/walkCard.styled.tsx
  client/src/components/card/walkCard/walkCard.tsx
  client/src/components/nav/NavBar.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/myPage/myPage.styled.tsx
  client/src/pages/walkMate/WalkMate.styled.tsx
  client/src/pages/walkMate/WalkMate.tsx
Labels: 스타일, 추가, 주기능

#131 Fix & Feat: Build 시 에러 수정 및 마이페이지 산책 게시물 리스트 무한스크롤 구현
  client/src/common/select/select.styled.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/userpage/UserPage.tsx
  client/src/pages/walkMate/WalkMate.styled.tsx
  client/src/pages/walkMate/WalkMate.tsx
  client/tsconfig.json
Labels: 스타일, 수정, 빌드

#132 Fix: 산책페이지, 댓글페이지 수정
  client/src/common/button/Button.tsx
  client/src/common/comment/Comment.tsx
  client/src/common/comment/feedComment.tsx/FeedComment.tsx
  client/src/components/follow-list/FollowList.tsx
  client/src/components/pet/PetInfo.tsx
  client/src/pages/feedPopUp/FeedPopUp.tsx
  client/src/pages/userpage/UserPage.tsx
  client/src/pages/walkEditing/WalkEditing.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
  client/src/pages/walkMate/WalkMate.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
  client/src/util/changeDateFormat.ts
  client/src/util/changeTiem.ts
Labels: 버그, 수정, 리팩토링

#136 Fix: CSS 수정 (카카오맵, 웰컴 팝업, 마이페이지, 유저페이지, 펫 등록)
  client/src/common/comment/comment.styled.tsx
  client/src/common/popup/popup.styled.tsx
  client/src/common/select/Select.tsx
  client/src/components/follow-list/followList.styled.tsx
  client/src/components/map-make/Map.tsx
  client/src/components/map-show/ShowMap.tsx
  client/src/components/pet/PetInfo.tsx
  client/src/components/pet/petInfo.styled.tsx
  client/src/components/pet/petProfile/PetProfile.tsx
  client/src/components/pet/petProfile/petProfile.styled.tsx
  client/src/components/user_my_page/pet-container/petContainer.styled.tsx
  client/src/components/user_my_page/petinfo-box/petInfoBox.styled.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/myPage/myPage.styled.tsx
  client/src/pages/userpage/UserPage.tsx
  client/src/util/changeDateFormat.ts
Labels: 스타일, 수정

#146 [FE][Fix]: 카카오 맵 수정
  client/src/components/follow-list/followList.styled.tsx
  client/src/components/map-make/Map.tsx
  client/src/pages/walkMate/WalkMate.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
Labels: 버그, 수정

#147 [FE][Build}: pwa 추가
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/apple-touch-icon-114x114.png
  client/public/apple-touch-icon-120x120.png
  client/public/apple-touch-icon-144x144.png
  client/public/apple-touch-icon-152x152.png
  client/public/apple-touch-icon-57x57.png
  client/public/apple-touch-icon-60x60.png
  client/public/apple-touch-icon-72x72.png
  client/public/apple-touch-icon-76x76.png
  client/public/code.txt
  client/public/favicon-128.png
  client/public/favicon-16x16.png
  client/public/favicon-196x196.png
  client/public/favicon-32x32.png
  client/public/favicon-96x96.png
  client/public/favicon.ico
  client/public/favicon.svg
  client/public/icon-512x512.png
  client/public/manifest.json
  client/public/mstile-144x144.png
  client/public/mstile-150x150.png
  client/public/mstile-310x150.png
  client/public/mstile-310x310.png
  client/public/mstile-70x70.png
  client/public/vite.svg
  client/sw.ts
  client/tsconfig.json
  client/vite.config.ts
Labels: 추가, 빌드

#155 [FE][Fix]: 지도, Select 수정, 팝업 수정
  client/index.html
  client/src/common/comment/Comment.tsx
  client/src/common/popup/Popup.tsx
  client/src/common/popup/popup.styled.tsx
  client/src/common/select/Select.tsx
  client/src/components/map-make/Map.tsx
  client/src/components/user_my_page/pet-container/PetContainer.tsx
  client/src/main.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/userpage/UserPage.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
Labels: 수정, 리팩토링

#159 Feat: 산책 게시물 페이지 에러처리 추가
  client/src/common/comment/Comment.tsx
  client/src/common/input/Input.styled.tsx
  client/src/pages/walkMate/WalkMate.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
Labels: 리팩토링

#160 Refactor&Feat: query onError 코드 추가 및 팝업창 리팩토링
  client/src/common/comment/Comment.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/pages/feedPopUp/FeedPopUp.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
  client/src/util/changeTime.ts
Labels: 추가, 수정, 리팩토링, 삭제

#161 Fix: 화면 분기 처리(홈, 유저 페이지, 마이 페이지)
  client/src/main.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/userpage/UserPage.tsx
Labels: 수정

#162 Fix&Style: 삭제 보이지 않는 에러 수정
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/components/user_my_page/pet-container/PetContainer.tsx
Labels: 버그, 스타일, 수정

#163 Feat: useCheckLogin hook 작성
  client/src/hook/useCheckLogin.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/walkMate/WalkMate.tsx
Labels: 추가

#165 Remove: lint 에러 코드 삭제
  client/src/pages/home/Home.tsx
Labels: 버그, 삭제

#166 Fix: 산책 페이지, 상세 페이지, 수정 페이지, 생성 페이지 라우팅 처리
  client/src/hook/useCheckLogin.tsx
  client/src/pages/walkEditing/WalkEditing.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
  client/src/pages/walkMate/WalkMate.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
Labels: 버그, 수정, 리팩토링

#167 Refactor: 펫 등록, 삭제 시 헤더컴포넌트 실시간 반영
  client/src/common/header/Header.tsx
  client/src/components/nav/NavBar.tsx
  client/src/pages/loading/Loading.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/store/Context.tsx
Labels: 리팩토링

#181 Fix&Style: 피드 게시물, 피드팝업 수정
  client/index.html
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/components/card/sidenav/SideNav.tsx
  client/src/components/pet/petProfile/PetProfile.tsx
  client/sw.js
Labels: 버그, 스타일, 수정

#183 Fix: 확장명 추가
  client/src/App.tsx
  client/src/api/mutationfn.ts
  client/src/api/queryfn.ts
  client/src/common/button/Button.tsx
  client/src/common/button/button.styled.tsx
  client/src/common/comment/Comment.tsx
  client/src/common/comment/feedComment/FeedComment.styled.tsx
  client/src/common/comment/feedComment/FeedComment.tsx
  client/src/common/footer/Footer.tsx
  client/src/common/header/Header.styled.tsx
  client/src/common/header/Header.tsx
  client/src/common/input/Input.styled.tsx
  client/src/common/input/feedInput/FeedInput.tsx
  client/src/common/popup/Popup.tsx
  client/src/common/profile/Profile.tsx
  client/src/common/select/Select.tsx
  client/src/components/card/feed-card/FeedCard.tsx
  client/src/components/card/feedwritecard/FeedWriteCard.tsx
  client/src/components/card/sidenav/SideNav.tsx
  client/src/components/card/walk-card/walkCard.tsx
  client/src/components/follow-list/FollowList.tsx
  client/src/components/loading/LoadingComponent.tsx
  client/src/components/map-make/Map.tsx
  client/src/components/nav/NavBar.tsx
  client/src/components/notice/NoticeNoData.tsx
  client/src/components/notice/NoticeNotWrite.tsx
  client/src/components/notice/NoticeOnlyOwner.tsx
  client/src/components/notice/NoticeServerError.tsx
  client/src/components/pet/PetInfo.tsx
  client/src/components/pet/petProfile/PetProfile.tsx
  client/src/components/plus-button/PlusBtn.tsx
  client/src/components/subscribe/Subscribe.tsx
  client/src/components/toast/Toast.tsx
  client/src/components/user_my_page/pet-container/PetContainer.tsx
  client/src/components/user_my_page/petinfo-box/PetInfoBox.tsx
  client/src/hook/useZipCode.tsx
  client/src/pages/feedPopUp/FeedPopUp.tsx
  client/src/routers/routers.tsx
  client/src/store/Context.tsx
  client/src/types/feedTypes.ts
  client/src/types/userType.ts
  client/src/types/walkType.ts
  client/src/util/parseImg.ts
Labels: 수정

#185 Fix: 산책 게시글 로직 및 파일 확장자 명 수정
  client/index.html
  client/src/components/map-make/Map.tsx
  client/src/components/notice/NoticeNoData.tsx
  client/src/components/notice/NoticeNotWrite.tsx
  client/src/components/notice/NoticeOnlyOwner.tsx
  client/src/components/notice/NoticeServerError.tsx
  client/src/pages/myPage/MyPage.tsx
  client/src/pages/notFound/NotFound.styled.tsx
  client/src/pages/notFound/NotFound.tsx
  client/src/pages/userpage/UserPage.tsx
  client/src/pages/walkEditing/WalkEditing.tsx
  client/src/pages/walkFeed/WalkFeed.styled.tsx
  client/src/pages/walkFeed/WalkFeed.tsx
  client/src/pages/walkMate/WalkMate.tsx
  client/src/pages/walkPosting/WalkPosting.tsx
Labels: 수정

#186 Refactor&Remove: query staleTime 추가
  client/src/pages/feedPopUp/FeedPopUp.tsx
  client/src/pages/home/Home.tsx
Labels: 수정, 삭제

#187 Refactor: 산책 게시글 페이지 모집중 카드컴포넌트 시간 수정
  client/src/pages/walkMate/WalkMate.tsx
Labels: 리팩토링

#188 Refactor&Fix: 피드 리스트, 팝업 네브바 에러 수정
  client/src/components/card/feed-card/FeedCard.styled.tsx
  client/src/components/card/sidenav/SideNav.tsx
  client/src/pages/feedPopUp/FeedPopUp.styled.tsx
  client/src/pages/home/Home.styled.tsx
  client/src/pages/home/Home.tsx
Labels: 버그, 스타일, 수정, 리팩토링, 삭제

#189 Remove: 알림 토스트 관련 코드 제거
  client/src/components/card/sidenav/SideNav.tsx
  client/src/components/toast/Toast.styled.tsx
  client/src/components/toast/Toast.tsx
  client/src/pages/home/Home.tsx
Labels: 삭제

#190 Remove: 알림 토스트 관련 코드 제거
  client/src/pages/feedPopUp/FeedPopUp.tsx
Labels: 삭제

#208 Fix: PetPopUP 수정
  client/src/components/pet/PetInfo.tsx
  client/src/components/pet/petInfo.styled.tsx
Labels: 수정, 리팩토링

#196 Fix: 회원정보 뒤로가기 버튼 추가
  client/src/pages/info/Info.tsx
Labels: 버그

#197 Fix: 산책글쓰기 수정페이지 X버튼 클릭 시, 이전페이지로 이동
  client/src/pages/walkEditing/WalkEditing.tsx
Labels: 버그

#213 [FE][Feat]: image 압축 기능 추가
  client/src/assets/spin.svg
  client/src/components/pet/petProfile/PetProfile.tsx
  client/src/components/spin/Spin.tsx
  client/src/util/imageCompressOption.ts
  client/src/util/parseImg.ts
  client/tailwind.config.js
Labels: 수정

#216 Fix: home 무한 스크롤 수정
  client/src/pages/home/Home.tsx
Labels: 버그, 수정

#218 Fix: 새로고침시, 데이터 유지되는 상황 수정
  client/src/pages/home/Home.tsx
Labels: 수정

#219 Fix: home 쿼리 에러 해결
  client/src/pages/home/Home.tsx
Labels: 수정, 삭제
